name: Publish a preview build

on:
  issue_comment:
    types: created

jobs:
  publish-preview:
    name: Publish build preview
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout pull request
        run: gh pr checkout "${PR_NUMBER}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: yarn
      - run: yarn --immutable
      - name: Get commit SHA
        id: commit-sha
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - run: yarn prepare-preview-builds @metamask-previews ${{ steps.commit-sha.outputs.COMMIT_SHA }}
      - run: yarn build
      - name: Publish preview build
        run: yarn publish-previews
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.PUBLISH_PREVIEW_NPM_TOKEN }}
      - name: Generate preview build message
        run: yarn ts-node scripts/generate-preview-build-message.ts
      - name: Post build preview in comment
        run: gh pr comment "${PR_NUMBER}" --body-file preview-build-message.txt
        env:
          COMMIT_SHA: ${{ steps.commit-sha.outputs.COMMIT_SHA }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }}
